-- Learnix Research RAG Engine - Supabase PostgreSQL Database Schema Creation Script
-- Execute this script in your Supabase Dashboard -> SQL Editor to initialize all 7 cloud tables.

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    email TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    salt TEXT NOT NULL,
    avatar TEXT,
    created_at DOUBLE PRECISION NOT NULL
);

-- 2. Sessions Table
CREATE TABLE IF NOT EXISTS public.sessions (
    token TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);

-- 3. OTPs Table
CREATE TABLE IF NOT EXISTS public.otps (
    email TEXT PRIMARY KEY,
    otp TEXT NOT NULL,
    expires DOUBLE PRECISION NOT NULL,
    purpose TEXT NOT NULL
);

-- 4. Chat History Table
CREATE TABLE IF NOT EXISTS public.chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    role TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
);

-- 5. Saved Papers Table
CREATE TABLE IF NOT EXISTS public.saved_papers (
    email TEXT NOT NULL,
    paper_id TEXT NOT NULL,
    title TEXT,
    authors TEXT,
    abstract TEXT,
    source TEXT,
    source_id TEXT,
    attack_vector TEXT,
    url TEXT,
    saved_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (email, paper_id)
);

-- 6. Critiques Table
CREATE TABLE IF NOT EXISTS public.critiques (
    id TEXT PRIMARY KEY,
    title TEXT,
    authors TEXT,
    year INT,
    source TEXT,
    source_id TEXT,
    url TEXT,
    section TEXT,
    attack_vector TEXT,
    target TEXT,
    risk_level TEXT,
    skepticism_score DOUBLE PRECISION,
    replication_prob DOUBLE PRECISION,
    paragraph_type TEXT,
    adversarial_tag TEXT,
    text TEXT,
    raw_text TEXT,
    severity TEXT,
    mitigation_suggestion TEXT,
    updated_at DOUBLE PRECISION
);

-- 7. Hotspots Cache Table
CREATE TABLE IF NOT EXISTS public.hotspots_cache (
    cache_key TEXT PRIMARY KEY,
    cache_date TEXT NOT NULL,
    data JSONB NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);

-- Enable Row Level Security (RLS) & Add Public Access Policies for API Key Access
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_papers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.critiques ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hotspots_cache ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read/write on users" ON public.users;
CREATE POLICY "Allow public read/write on users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write on sessions" ON public.sessions;
CREATE POLICY "Allow public read/write on sessions" ON public.sessions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write on otps" ON public.otps;
CREATE POLICY "Allow public read/write on otps" ON public.otps FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write on chat_history" ON public.chat_history;
CREATE POLICY "Allow public read/write on chat_history" ON public.chat_history FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write on saved_papers" ON public.saved_papers;
CREATE POLICY "Allow public read/write on saved_papers" ON public.saved_papers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write on critiques" ON public.critiques;
CREATE POLICY "Allow public read/write on critiques" ON public.critiques FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read/write on hotspots_cache" ON public.hotspots_cache;
CREATE POLICY "Allow public read/write on hotspots_cache" ON public.hotspots_cache FOR ALL USING (true) WITH CHECK (true);
